export const formErrors = {
  required: {
    default: "Este campo es obligatorio",
    email: "Debes ingresar un correo válido",
    name: "El nombre es obligatorio",
    lastName: "El apellido es obligatorio",
    password: "La contraseña es obligatoria",
    role: "El rol de usuario es obligatorio",
    serialNumber: "El número de serie es obligatorio",
    description: "La descripción es obligatoria",
    location: "La ubicación es obligatoria",
    minStock: "El stock mínimo es obligatorio",
    phone: "El número de teléfono es obligatorio",
  },
  invalid: {
    email: "El formato del correo no es válido",
    number: "Debes ingresar un número válido",
    date: "La fecha ingresada no es válida",
    phone: "El número de teléfono no es válido",
    RUT: "El RUT ingresado no es válido",
    name: "El nombre solo puede contener letras",
    lastName: "El apellido solo puede contener letras",
    serialNumber:
      "El número de serie solo puede contener letras, números y guiones",
    minStock: "El valor debe ser un número entero válido",
    location: "La ubicación debe ser un UUID válido",
  },
  length: {
    passwordMin: "La contraseña debe tener al menos 8 caracteres",
    nameMax: "El nombre no puede tener más de 50 caracteres",
    lastNameMax: "El apellido no puede tener más de 50 caracteres",
    serialNumberMax: "El número de serie no debe superar los 30 caracteres",
    descriptionMax: "La descripción no debe superar los 100 caracteres",
    locationMax: "La ubicación no debe superar los 50 caracteres",
    minStockMin: "El stock mínimo no puede ser negativo",
    phoneMax: "El número de teléfono no puede tener más de 15 dígitos",
  },
  password: {
    noUppercase: "Debe contener al menos una letra mayúscula",
    noLowercase: "Debe contener al menos una letra minúscula",
    noNumber: "Debe contener al menos un número",
    noSymbol: "Debe contener al menos un carácter especial",
    mismatch: "Las contraseñas no coinciden",
  },
  confirmPassword: {
    mismatch: "Las contraseñas no coinciden",
  },
};
